### ISSUE TITLE
[fork]: The skid menus (basically every free and cheap gta 5 menu)

### ISSUE THREAD

**Issue by shrekshrek214** [YimMenu/yimmenu.github.io#1]
### Repository

The "Skid Menus"

### Short description

- Jaykoza : https://ghax.eu/ - https://forum.jaykoza.de/
- Disturbed : https://w1tch.net/
- Position : https://positioncheats.company/
- Explosive : https://explosivemenu.com/
- Skript : https://skript.gg/
- Spectral : http://spectral.website/
- MaverickCheats : https://maverickcheats.net/
- 0xcheats : https://vk.com/0xcheats/ | https://0xcheats.net/
- Astrocheats : https://astrocheats.net/
- Raiden : https://raiden.gg/
- Dope : https://dopemenu.createaforum.com/
- Hextic : http://hextichacks.com/
- Aspire : https://aspire.black/
- XCheats : https://www.xcheats.co.uk/
- X-Force : https://xforce.menu/
- Stand : https://stand.gg/
- Ovix : https://ovix.one/
- Syslx : https://syslx-menu.com/
- Phantom-X : https://phantom-x.info/ | https://vk.com/phantomcommunity/ | https://vk.com/pxraymond/
- Fierro : https://fierrohack.ru/ | https://vk.com/fierro_menu/
- Menace : https://justmenace.com/
- Serenity : https://www.serenitymenu.com/
- Midnight : https://midnight.im/
- Frontier : https://frontiercheats.com/
- Circuit : https://circuit.menu/
- Bunny : https://bunnymenu.cc/
- Rebound : https://reboundcheats.org/
- Soviet : https://sovietcheats.com/
- Sasavn : https://sasavn.ru/ - https://vk.com/sasavnhack
- Ethereal : https://etherealmenu.cn/
- Purge : https://gtavpurge.xyz/login.php
- Argon : https://argonmenu.com/
- North : https://north.lol/
- Reborn : https://reborncheats.com/
- Lounge : https://loungemenu.net/
- Spectrum : https://spectrum.menu/
- Nightfall : https://nfcheats.com/
- GCheats : https://gcheats.io/
- Victory : https://victory.menu/
- Slime : https://slimecheats.com/
- Archlight : https://archlightmenu.com/
- Cretin : https://cretinmenu.com/ 
- Atlas : https://atlasmenu.net/
- Moneybot : https://moneybot.cash/
- Monster : https://gtamonsters.com/
- Fikit : https://fikitcheats.com/
- Crimson : https://crimson-menu.net/
- Ignite : https://ignite.rip/
- Challenger : https://challengermenu.com/
- Open : https://opengta.menu/

### Fork checklist

- [X] My fork is based on YimMenu.
- [X] My fork is open source.
- [X] My fork has notable changes compared to vanilla YimMenu (like different GUI or original features).
- [X] My fork does not track its users (including launchers & APIs).

**Comment by GeopJr** [comment]
Uhm, I don't think most of them are YimMenu forks and clearly not comply with the requirements.

![image](https://user-images.githubusercontent.com/18014039/234076515-adbc1295-a4de-43bc-a0e3-0fbbec66910c.png)

cc: @Yimura

**Comment by Yimura** [comment]
Idk what you were planning by posting this list here?

**Comment by shrekshrek214** [comment]
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/49670222/234080464-47aec308-153d-452f-8a8f-6d50d71e6069.png">
I think this would look really good is all I'm saying
