### ISSUE TITLE
[fork]: 艾洛佩斯伽的专属yim

### ISSUE THREAD

**Issue by zcx0508** [YimMenu/yimmenu.github.io#17]
### Repository

专属

### Short description

This is a private Yim that is not used publicly

### Fork checklist

- [X] My fork is based on YimMenu.
- [X] My fork is open source.
- [X] My fork has notable changes compared to vanilla YimMenu (like different GUI or original features).
- [X] My fork does not track its users (including launchers & APIs).

**Comment by GeopJr** [comment]
> This is a private Yim that is not used publicly

> :ballot_box_with_check:  My fork is open source.
