### ISSUE TITLE
[fork]: Aboba

### ISSUE THREAD

**Issue by BigCheater** [YimMenu/yimmenu.github.io#2]
### Repository

Aboba

### Short description

Abnoba

### Fork checklist

- [X] My fork is based on YimMenu.
- [X] My fork is open source.
- [X] My fork has notable changes compared to vanilla YimMenu (like different GUI or original features).
- [X] My fork does not track its users (including launchers & APIs).

**Comment by GeopJr** [comment]
not a menu, not open source, not a fork of yimmenu
