### ISSUE TITLE
[fork]: 

### ISSUE THREAD

**Issue by CelkaTeam** [YimMenu/yimmenu.github.io#22]
### Repository

test fork

### Short description

tesk fork

### Fork checklist

- [X] My fork is based on YimMenu.
- [X] My fork is open source.
- [X] My fork has notable changes compared to vanilla YimMenu (like different GUI or original features).
- [X] My fork does not track its users (including launchers & APIs).

**Comment by GeopJr** [comment]
Don't test here. If you don't have a fork don't bother filling it in.
