### ISSUE TITLE
[fork]: add this options the menu please

### ISSUE THREAD

**Issue by BarsamGt** [YimMenu/yimmenu.github.io#39]
### Repository

Yimmenu

### Short description

hello ownership by yimmenu please add this options your mod menu is thr best menu free in the world but notthing full please add this thank you please please add crash becuse all menu have a crash game

Spofing id
Rockstar developer flag
Rockstar Qa flag
Cheating Flag Spoof
 Another player
Crash game for trolls 
Cage player 
Spofing IP 
Auto heal
no combat no roll cooldown
freaze players
Kick all player
crash all player
Fake monydrop
Mugger Loop
praticle spam
infifity phone ringing
command box script
Give script host 
Attacker player troll
Ram player
infinifty loading screen for player 

Thank you❤️❤️

### Fork checklist

- [X] My fork is based on YimMenu.
- [X] My fork is open source.
- [X] My fork has notable changes compared to vanilla YimMenu (like different GUI or original features).
- [X] My fork does not track its users (including launchers & APIs).

**Comment by BarsamGt** [comment]
please do it options crash game

**Comment by GeopJr** [comment]
Wrong repo

https://github.com/YimMenu/YimMenu/issues/new?assignees=&labels=request&projects=&template=feature_request.yml&title=%5BRequest%5D%3A+
