### ISSUE TITLE
[fork]: ddfo

### ISSUE THREAD

**Issue by linus467423** [YimMenu/yimmenu.github.io#45]
### Repository

gta

### Short description

fgfgg

### Fork checklist

- [X] My fork is based on YimMenu.
- [X] My fork is open source.
- [X] My fork has notable changes compared to vanilla YimMenu (like different GUI or original features).
- [X] My fork does not track its users (including launchers & APIs).

**Comment by linus467423** [comment]
gg

**Comment by GeopJr** [comment]
Why are you doing this?
