### ISSUE TITLE
kaedence

### ISSUE THREAD

**Issue by unkownkilla** [YimMenu/yimmenu.github.io#47]
### Repository

gta 5

### Short description

its clean

### Fork checklist

- [X] My fork is based on YimMenu.
- [X] My fork is open source.
- [X] My fork has notable changes compared to vanilla YimMenu (like different GUI or original features).
- [X] My fork does not track its users (including launchers & APIs).

**Comment by GeopJr** [comment]
If that's a fork based on yimmenu, please link the repo.
