### ISSUE TITLE
[fork]: 

### ISSUE THREAD

**Issue by Brzoza461** [YimMenu/yimmenu.github.io#49]
### Repository

hi i want play in a YimMenu

### Short description

hi im a player and i like troll my frends and other person

### Fork checklist

- [X] My fork is based on YimMenu.
- [X] My fork is open source.
- [X] My fork has notable changes compared to vanilla YimMenu (like different GUI or original features).
- [X] My fork does not track its users (including launchers & APIs).

**Comment by GeopJr** [comment]
this has nothing to do with anything
