### ISSUE TITLE
hi[fork]: 

### ISSUE THREAD

**Issue by K3liii7** [YimMenu/yimmenu.github.io#51]
### Repository

i

### Short description

i

### Fork checklist

- [X] My fork is based on YimMenu.
- [X] My fork is open source.
- [X] My fork has notable changes compared to vanilla YimMenu (like different GUI or original features).
- [X] My fork does not track its users (including launchers & APIs).

**Comment by GeopJr** [comment]
why, please read before you click random stuff.
