### ISSUE TITLE
[fork]: WEFWFSFSAWrw3efwfwq

### ISSUE THREAD

**Issue by Balintt-spec** [YimMenu/yimmenu.github.io#53]
### Repository

szeretemafaszt

### Short description

WEGWTWEGTTWGWGWGWGWDFEWEFWEFWFWEFWFWEFFFFWGFWEFWETWETWEGWERG WGWERGWERGERGWERTRRWEREWRRWERTWEWRTWERTERGEWEREGW3EGERWG EWGRWG WEFWFGWTWEWWWWWWWWFWWWFWR34R2FRWRTW34TRWERGWE4GHGERTGHETHRH2WERWEFGEWRWRWR WR WRTWER WERWERWER W4 TERGHERRHRRTHJRTWTW4HZGERTJR65JR56EGHAEW4RQGHEQHEREEZHE2WERHERHQEHJEJJREJRETJ

### Fork checklist

- [X] My fork is based on YimMenu.
- [X] My fork is open source.
- [X] My fork has notable changes compared to vanilla YimMenu (like different GUI or original features).
- [X] My fork does not track its users (including launchers & APIs).

**Comment by Balintt-spec** [comment]
hefdjhgqgfizutfroquZFGT1O8Q3

**Comment by GeopJr** [comment]
why, please read before you click random stuff.
