### ISSUE TITLE
[fork]: 

### ISSUE THREAD

**Issue by brianayres234** [YimMenu/yimmenu.github.io#54]
### Repository

hi

### Short description

rgredged

### Fork checklist

- [X] My fork is based on YimMenu.
- [X] My fork is open source.
- [X] My fork has notable changes compared to vanilla YimMenu (like different GUI or original features).
- [X] My fork does not track its users (including launchers & APIs).

**Comment by brianayres234** [comment]
gh

**Comment by brianayres234** [comment]
fdgdfrg

**Comment by brianayres234** [comment]
gdrgdfr

**Comment by GeopJr** [comment]
please read before spending time making and account and making spam issues
