### ISSUE TITLE
[fork]: 

### ISSUE THREAD

**Issue by lilmelonsito** [YimMenu/yimmenu.github.io#55]
### Repository

ok

### Short description

op

### Fork checklist

- [X] My fork is based on YimMenu.
- [X] My fork is open source.
- [X] My fork has notable changes compared to vanilla YimMenu (like different GUI or original features).
- [X] My fork does not track its users (including launchers & APIs).

**Comment by GeopJr** [comment]
please read before clicking random stuff.
