### ISSUE TITLE
[fork]: 

### ISSUE THREAD

**Issue by usernametom1104** [YimMenu/yimmenu.github.io#56]
### Repository

.

### Short description

bbiuhjhoihinokjnjhniojoihjoijiojpojojpojouihj08jijojoipjoijojoijoijoijjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj

### Fork checklist

- [X] My fork is based on YimMenu.
- [X] My fork is open source.
- [X] My fork has notable changes compared to vanilla YimMenu (like different GUI or original features).
- [X] My fork does not track its users (including launchers & APIs).

**Comment by GeopJr** [comment]
read before clicking random things
