### ISSUE TITLE
[fork]: tgguy

### ISSUE THREAD

**Issue by Connerfincv99** [YimMenu/yimmenu.github.io#57]
### Repository

gyughyu

### Short description

ft67t7tygb

### Fork checklist

- [X] My fork is based on YimMenu.
- [X] My fork is open source.
- [X] My fork has notable changes compared to vanilla YimMenu (like different GUI or original features).
- [X] My fork does not track its users (including launchers & APIs).

**Comment by GeopJr** [comment]
this form is not a captcha, read before clicking random stuff
