### ISSUE TITLE
[fork]: 

### ISSUE THREAD

**Issue by tim969** [YimMenu/yimmenu.github.io#58]
### Repository

w

### Short description

w

### Fork checklist

- [X] My fork is based on YimMenu.
- [X] My fork is open source.
- [X] My fork has notable changes compared to vanilla YimMenu (like different GUI or original features).
- [X] My fork does not track its users (including launchers & APIs).

**Comment by GeopJr** [comment]
this is not a captcha, don't click random stuff.
