### ISSUE TITLE
[fork]: yimmenu

### ISSUE THREAD

**Issue by LukasKrentz** [YimMenu/yimmenu.github.io#60]
### Repository

YimMenu

### Short description

am tryna change something without any knowledge of c++

### Fork checklist

- [X] My fork is based on YimMenu.
- [X] My fork is open source.
- [X] My fork has notable changes compared to vanilla YimMenu (like different GUI or original features).
- [X] My fork does not track its users (including launchers & APIs).

**Comment by GeopJr** [comment]
then why did u open an issue? please read before clicking random stuff
