### ISSUE TITLE
[fork]: 

### ISSUE THREAD

**Issue by Cold425** [YimMenu/yimmenu.github.io#61]
### Repository

g6zg6tfiig5

### Short description

cayo jnhv,bzcgkkhvtgczizubztu

### Fork checklist

- [X] My fork is based on YimMenu.
- [X] My fork is open source.
- [X] My fork has notable changes compared to vanilla YimMenu (like different GUI or original features).
- [X] My fork does not track its users (including launchers & APIs).

**Comment by GeopJr** [comment]
please read before clicking random things
