### ISSUE TITLE
[fork]: je veut ajouter 

### ISSUE THREAD

**Issue by djo0207** [YimMenu/yimmenu.github.io#63]
### Repository

test

### Short description

dsfsdfsdfsdfsfdsfsdfsdfdsdfdsfsd

### Fork checklist

- [X] My fork is based on YimMenu.
- [X] My fork is open source.
- [X] My fork has notable changes compared to vanilla YimMenu (like different GUI or original features).
- [X] My fork does not track its users (including launchers & APIs).

**Comment by GeopJr** [comment]
This is not the place to make test issues, please read before clicking random stuff
