### ISSUE TITLE
[fork]: 

### ISSUE THREAD

**Issue by cj12345678990** [YimMenu/yimmenu.github.io#65]
### Repository

fdfsd

### Short description

fddf

### Fork checklist

- [X] My fork is based on YimMenu.
- [X] My fork is open source.
- [X] My fork has notable changes compared to vanilla YimMenu (like different GUI or original features).
- [X] My fork does not track its users (including launchers & APIs).

**Comment by GeopJr** [comment]
dont click random stuff
