### ISSUE TITLE
[fork]: Please add <buke132> to the website

### ISSUE THREAD

**Issue by buke132** [YimMenu/yimmenu.github.io#66]
### Repository

veichle mod

### Short description

bdf

### Fork checklist

- [X] My fork is based on YimMenu.
- [X] My fork is open source.
- [X] My fork has notable changes compared to vanilla YimMenu (like different GUI or original features).
- [X] My fork does not track its users (including launchers & APIs).

**Comment by buke132** [comment]
godd

**Comment by buke132** [comment]
cars

**Comment by buke132** [comment]
v

**Comment by buke132** [comment]
sd

**Comment by buke132** [comment]
s

**Comment by buke132** [comment]
s

**Comment by buke132** [comment]
s

**Comment by buke132** [comment]
s

**Comment by buke132** [comment]
e

**Comment by GeopJr** [comment]
no. And stop spamming.
