### ISSUE TITLE
[fork]: e

### ISSUE THREAD

**Issue by phsrx** [YimMenu/yimmenu.github.io#68]
### Repository

https://github.com/phsrx/FeralMenu

### Short description

eeeee
ee

### Fork checklist

- [X] My fork is based on YimMenu.
- [X] My fork is open source.
- [X] My fork has notable changes compared to vanilla YimMenu (like different GUI or original features).
- [X] My fork does not track its users (including launchers & APIs).

**Comment by GeopJr** [comment]
> My fork has notable changes compared to vanilla YimMenu (like different GUI or original features).

The linked source code does not list any changes.

**Comment by GeopJr** [comment]
No. This issue is for submitting YimMenu forks, if you don't have a fork ready then don't open an issue.
