### ISSUE TITLE
[fork]: yhea

### ISSUE THREAD

**Issue by yornowismine** [YimMenu/yimmenu.github.io#71]
### Repository

awasda

### Short description

das

### Fork checklist

- [X] My fork is based on YimMenu.
- [X] My fork is open source.
- [X] My fork has notable changes compared to vanilla YimMenu (like different GUI or original features).
- [X] My fork does not track its users (including launchers & APIs).

**Comment by GeopJr** [comment]
stop clicking random stuff.
