### ISSUE TITLE
[fork]: 

### ISSUE THREAD

**Issue by Conner30** [YimMenu/yimmenu.github.io#74]
### Repository

awdwada

### Short description

dwadwa

### Fork checklist

- [X] My fork is based on YimMenu.
- [X] My fork is open source.
- [X] My fork has notable changes compared to vanilla YimMenu (like different GUI or original features).
- [X] My fork does not track its users (including launchers & APIs).

**Comment by GeopJr** [comment]
This is not a captcha, read before you click random stuff.
