### ISSUE TITLE
[fork]: mods

### ISSUE THREAD

**Issue by bruhhopr2s** [YimMenu/yimmenu.github.io#75]
### Repository

money god mode god mode viechle

### Short description

need some help with the money and the god mode because all the modders are typing me and killing me for no reason anf the people who I'm fighting have God mode and I don't like it.

### Fork checklist

- [X] My fork is based on YimMenu.
- [X] My fork is open source.
- [X] My fork has notable changes compared to vanilla YimMenu (like different GUI or original features).
- [X] My fork does not track its users (including launchers & APIs).

**Comment by GeopJr** [comment]
wrong repo
