### ISSUE TITLE
[fork]: 

### ISSUE THREAD

**Issue by gwwwf** [YimMenu/yimmenu.github.io#8]
### Repository

Yim meni

### Short description

Hey why should I write this I just want to play with this menu
bro

### Fork checklist

- [X] My fork is based on YimMenu.
- [X] My fork is open source.
- [X] My fork has notable changes compared to vanilla YimMenu (like different GUI or original features).
- [X] My fork does not track its users (including launchers & APIs).

**Comment by GeopJr** [comment]
This is for yimmenu forks. Just click the download button that's some pixels above the one that brought you here.
